name: CI

on:
  # Trigger the workflow on push to the master branch
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: rscohn2/oneapi-spec:latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --quiet -r requirements.txt
          python doc.py html
          python doc.py latexpdf
          python doc.py spelling
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
